---
- name: Set apt sources to nearest mirror
  template: >
    src=sources.list.j2
    dest=/etc/apt/sources.list
    owner=root group=root mode=644
  sudo: yes
  notify: run apt-get update

- name: Upgrade installed packages
  apt: upgrade=yes update_cache=yes cache_valid_time=3600
  when: apt_upgrade == true
